# Generated by Django 4.0.3 on 2022-03-19 15:14

from django.db import migrations, models
import myapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=60)),
                ('edition', models.IntegerField()),
                ('description', models.CharField(max_length=60)),
                ('ISBN', models.CharField(max_length=13)),
                ('subjects', models.CharField(max_length=60, validators=[myapi.models.subject_validate])),
                ('rating', models.FloatField()),
                ('books_available', models.CharField(max_length=60)),
                ('book_Image_url', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 0.0), ('rating__lte', 5.0)), name='rating_range'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('ISBN__length__gte', 13), ('ISBN__length__lte', 13)), name='ISBN_Length_range'),
        ),
    ]
