# Generated by Django 4.0.3 on 2022-03-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
