# Generated by Django 4.0.3 on 2022-03-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_fine_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
